# Generated by Django 3.2.4 on 2021-07-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0003_user_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ProfilePic',
            field=models.FileField(default='default.jpg', upload_to='users/'),
        ),
    ]
